[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Prędkość monitora szeregowego (musi być zgodna z Serial.begin w kodzie)
monitor_speed = 115200

; Prędkość wgrywania kodu po kablu (dla oszczędności czasu)
upload_speed = 460800

; Ustawienie partycji w pamięci Flash. 
; Używamy "min_spiffs.csv", co daje dużo miejsca na aplikację (potrzebne do aktualizacji OTA!)
board_build.partitions = min_spiffs.csv

; Lista wszystkich bibliotek, które PlatformIO musi samo pobrać
lib_deps =
    mandulaj/PZEM-004T-v30 @ ^1.1.2
    seithan/Easy Nextion Library @ ^1.0.6
    dfrobot/DFRobot_GP8403 @ ^1.0.0
    adafruit/Adafruit ADS1X15 @ ^2.4.0
    br3ttb/PID @ ^1.2.1
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14