[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Prędkość monitora portu szeregowego (taka sama jak w Serial.begin)
monitor_speed = 115200

; Biblioteki wymagane do działania Serwera
lib_deps =
    knolleary/PubSubClient @ ^2.8